http:
 #region routers
  routers:
    ombi:
      entryPoints:
        - "https"
      rule: "Host(`unifi.ektra.moln.page`)"
      middlewares:
        - default-headers
      tls: {}
      service: unifi
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.ektra.moln.page`)"
      middlewares:
        - default-headers
        - addprefix-pihole
      tls: {}
      service: pihole


#endregion
#region services
  services:
    unifi:
      loadBalancer:
        servers:
          - url: "https://192.168.1.8:8443/"
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.8:80"
        passHostHeader: true

#endregion
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https


    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
